# basic
title: Timly
subtitle: Handmade diamond
favicon: https://hexo.io/icon/favicon-96x96.png

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: http://www.microux.com/microux-logo.svg
# logo: http://www.uxlearn.com/wp-content/themes/uxlearn/build/assets/img/logo-mini-uxlearn.svg

# disqus comments
# disqus_shortname: timly

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# main menu #
nav:
#   home: .
#   archive: archives
  О проекте: about
  RSS: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  # github: https://github.com/GallenHu
  # weibo: http://weibo.com/10010800
  mail: mailto:ux101@yandex.ru
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: <ul><li><a href="https://github.com/GallenHu/hexo-theme-Daily">如何自定义这里的内容(配置教程)?</a></li></ul>

footer: